# Generated by Django 5.1.1 on 2024-09-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_flower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
